name = input("请输入公司名称\n")
my_name = input("请输入你的名字\n")
phone = int(input("请输入你的电话\n"))
email = input("请输入你的邮箱\n")
title = input("请输入你的职位\n")

print("*"*50)
print("公司的名称是:%s"%name)
print("\n")
print("\n")
print("职位是:%s"%title)
print("\n")
print("姓名:%s"%my_name)
print("电话:%d"%phone)
print("邮箱:%s"%email)
print("*"*50)
